FROM mcr.microsoft.com/dotnet/core/sdk:3.1 

ENV DOTNET_USE_POLLING_FILE_WATCHER 1
ENV ASPNETCORE_ENVIRONMENT=Docker

RUN mkdir app
WORKDIR /app

COPY ./*.sln .
COPY ./*.props .
COPY ./src/ ./src/
COPY ./test/ ./test/
COPY ./build/startup.sh .

RUN dotnet restore
RUN chmod +x ./startup.sh

# CMD tail -f /dev/null
CMD dotnet watch -p "src/ApiExercise.Host/" run --urls "http://0.0.0.0:5000;https://0.0.0.0:5001" --launch-profile Docker
