FROM mcr.microsoft.com/dotnet/core/sdk:3.1

ENV DOTNET_USE_POLLING_FILE_WATCHER 1
WORKDIR /app

RUN pwd
RUN ls -a

COPY *.sln ./
RUN ls -a

COPY src/ src/
COPY test/ test/
COPY build/startup.sh ./startup.sh

RUN pwd
RUN ls -a
RUN ls src
RUN ls test

RUN dotnet restore
RUN chmod +x ./startup.sh

ENTRYPOINT ./startup.sh
