version: "3"

services:
  apiexercise:
    build: ./
    container_name: apiexercise
    ports:
      - 5000:5000
      - 5001:5001
    volumes:
      - ./src:/app
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server
    container_name: sqlserver
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Password_123"
      MSSQL_PID: "Express"