FROM mcr.microsoft.com/dotnet/core/sdk:3.1 

ENV DOTNET_USE_POLLING_FILE_WATCHER 1

RUN mkdir app
WORKDIR /app

COPY ./*.sln .
COPY ./*.props .
COPY ./src/ ./src/
COPY ./test/ ./test/
COPY ./build/startup.sh .

RUN dotnet restore
RUN chmod +x startup.sh

RUN pwd
RUN ls
RUN cat startup.sh

ENTRYPOINT ./startup.sh