version: "3.7"

services:
  apiexercise:
    build:
      context: .
      dockerfile: Dockerfile-watching
    container_name: apiexercise
    ports:
      - 5000:5000
      - 5001:5001
    volumes:
      - type: volume
        source: mydata
        target: /src
        volume:
          nocopy: true
      - type: bind
        source: ./src
        target: /app/src
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server
    container_name: sqlserver
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Password_123"
      MSSQL_PID: "Express"

volumes:
  mydata: