FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build-env
WORKDIR /app

COPY . .

RUN dotnet publish -c Release -o '/app/output'

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
WORKDIR /app

COPY --from=build-env /app/output ./

EXPOSE 8085

ENTRYPOINT ["dotnet", "Host.dll"]