FROM microsoft/dotnet:sdk

ENV DOTNET_USE_POLLING_FILE_WATCHER 1

RUN mkdir app
WORKDIR /app

COPY . .

RUN dotnet restore

CMD dotnet watch run --urls "http://0.0.0.0:5000;https://0.0.0.0:5001"